name: cedu
description: "A free app to learn code stuff"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^13.0.0
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.7.0
  vibration: ^2.0.0
  intl: ^0.17.0
  flutter_markdown: ^0.7.4
  markdown_widget: ^2.3.2+6
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
